analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 106005,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 90397,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"team\\"\: {\\n    \\"id\\"\: 90397,\\n    \\"name\\"\: \\"My Team\\",\\n    \\"organization\\"\: {\\n      \\"id\\"\: 69625,\\n      \\"name\\"\: \\"Organization pyuniartha\\",\\n      \\"samlSSO\\"\: false\\n    }\\n  },\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 90397,\\n  \\"name\\"\: \\"My Team\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 69625,\\n    \\"name\\"\: \\"Organization pyuniartha\\",\\n    \\"samlSSO\\"\: false\\n  }\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
